version: "3.9"

services:
  database:
    image: postgres
    container_name: lavarelampago_database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=julia
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lavarelampago_db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
